## you probably need to change or comment/uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
scriptsdir: "WORKDIR/scripts"
resourcesdir: "PIPELINE_HOME/resources"
tools: "WORKDIR/tools.yaml"
cluster: "WORKDIR/cluster.json"
# annotations 
ref_gtf: "/data/Ziegelbauer_lab/resources/hg38/hg38.v36.gtf"
ref_fa: "/data/Ziegelbauer_lab/resources/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.v4/hg38_rRNA_masked_plus_rRNA_plus_viruses_plus_ERCC.fa"
#
# tab delimited samples file ... should have the following 4 columns
# sampleName	group path_to_R1_fastq	path_to_R2_fastq
#
samples: "WORKDIR/samples.tsv"
# tab delimited contrasts with 2 columns
# group1  group2
contrasts: "WORKDIR/contrasts.tsv"